size: 50
avatar_size: 5
picture_size: 5
length:
  page: 8
setting:
  all: "get_all"
  learned: "learned"
  not_learned: "not_learned"
  content: "{content}"
activities:
  followed: followed
  unfollowed: unfollowed
  learned: learned
avatar:
  list_user_avatar_size: "50x50"
  home_user_avatar_size: "200x200"
lesson:
  limit_words: 20
minimum_password: 6
maximum_email: 255
